export { IAssetState } from './asset';
export { IClientState } from './client';
export { IMessageState } from './message';
export { IPluginState } from './plugin';
export { IRoomState } from './room';
export { ISettingState } from './setting';
export { IStyleState, IMessageBodyMenuStyle, IPluginMessageTextInteractionStyle } from './style';
export { IUserState } from './user';
import { ISettingState } from './setting';
import { Store } from 'redux';
import { SagaMiddleware } from 'redux-saga';
import { RouterState } from 'react-router-redux';
import { IClientState } from './client';
import { IPluginState } from './plugin';
import { IUserState } from './user';
import { IRoomState } from './room';
import { IMessageState } from './message';
import { IAssetState } from './asset';
import { IStyleState } from './style';
export declare const routerHistory: any;
export declare const sagaMiddleware: SagaMiddleware<{}>;
export declare const store: Store<any>;
export declare type State = {
    setting: ISettingState;
    client: IClientState;
    plugin: IPluginState;
    user: IUserState;
    room: IRoomState;
    message: IMessageState;
    asset: IAssetState;
    style: IStyleState;
    router: RouterState;
};
